### PR TITLE
52MB image size, with some runtime complexity.

### PR DESCRIPTION
**Pull request by tprobinson**
This system of managing dependencies is a little more complicated, but more flexible. Running the container with certain flags will install Pip, APK, or compile header dependencies before running any other command.

This process only happens on the first run, giving more warm-up time in exchange for a smaller download and image storage size. However, a flat image can still be baked out of this process, which can be seen in the documentation.

The Dockerfiles for 2.7 and 3.4 are as close to the same file as I could get. It's possible that some additional logic could merge them, and then a tool ike Rocker could be used to just change the PYTHON_MAJOR_VERSION.

Any edits or suggestions are welcome.

### CODE REVIEW

**Comment by jfloff** [comment]
Hello, sorry for the delay!

I found this PR very interesting and it adds to the whole alpine-spirit that keeps things simple. Only problem is, its very different from the typical docker workflow. I'm inclined to accept this, but as a separate tag, let's say `alpine-python:slim`. That way, those who wants the smallest possible image and those that want a more typical docker workflow can choose between the two. 

Could you refactor your changes to be under `slim` directory?

**Comment by tprobinson** [comment]
Closing this for the new pull request

**Comment by tprobinson** [comment]
Oops, I didn't realize GitHub would take my changes into the same request! I moved the changes into slim directories, reworked the docs, and added a little convenient build script that I used for updating the image sizes. Let me know if there's any other changes you'd like to see, or if there's something wrong with the docs.

**Comment by jfloff** [comment]
Could you leave the non-slim dockerfiles as is? 

My goal with this is: who is not worried about image size could use the same-old docker syntax (what's on the repo today); who wants minimum image size uses the slim tag and deals with the extra runtime complexity.

So `alpine-python:2.7` links to today's Dockerfile and `alpine-python:2.7-slim` would link to your PR Dockerfile. This is what happens in the [main docker python repo](https://hub.docker.com/_/python/), e.g.

**Comment by tprobinson** [comment]
Oh, yes, that was completely my intent. The non slim dockerfiles do the same thing they did before, just with a few enhancements like being pinned against a specific version of Alpine, using the new --no-cache flag, installing Pip via easy_install, because it's a smaller install size that way on the Python3 images, and using dumb-init as PID 1, which will properly reap any child processes that Python might create and prevent zombie children.

**Comment by jfloff** [comment]
Ok, I was trying to find time to do a couple of tests on your changes, but I'm going to let them roll and ping you in case any issues appear. :)

Thank you so much for your contribution! 👍

**Comment by jfloff** [comment]
Quick question. I have another repo that has this one as base, I did a quick test (build and run) with the new image, and found out that git wasn't found. The packages, like you said, are all the same but git its no longer there for the new image. My guess is that perhaps `build-base` removed git dependency somewhere along the way and I didn't noticed it. 

Did you saw this behaviour with other dependencies? 

Still, I added git as dependency for the non-slim images. I just wan't to know if I'm missing any other "key" dependencies that would fit this repo.

**Comment by tprobinson** [comment]
I'm not sure what might have been in it before. Maybe 'linux-headers'? Most packages will build without it, but some want it. Other than that, I didn't notice anything that was obviously absent.

**Comment by jfloff** [comment]
Well, maybe its the alpine-way ;)

Thank you for your input!

**Pull request merged**
