### PR TITLE
Pass --enable-shared when compiling python.

### PR DESCRIPTION
**Pull request by lwm**
Closes https://github.com/jfloff/alpine-python/issues/28.

### CODE REVIEW

**Comment by lwm** [comment]
The CI failures seem to be unrelated? 

Everything built but the the last 'echo success' command is borked?

**Comment by tprobinson** [comment]
The final "echo success" command is a test to see if Python actually runs in the container once the build is complete. We've had a few builds where everything will appear successful but some library or other is mislinked, leading to a crash on actual usage, so that's what that command is for.

**Comment by lwm** [comment]
I see. So, then something is a miss. I'd better build this locally and find out.

I wonder, could we improve this command to see any stack trace / error of what is happening?

**Comment by jfloff** [comment]
@lwm That would be great! But I would leave that for another PR. For now just test locally so we can merge this 👍

**Comment by lwm** [comment]
Sounds good. 

On holidays now, so will get back to this in 2 weeks.

Feel free anyone to move it along if needed!

**Comment by lwm** [comment]
OK, I had a poke around and found out that:

```
$ docker build -t enable-shared-3-6 .
$ docker run -it enable-shared-3-6 /bin/bash 
bash-4.4# python
Segmentation fault (core dumped)
```

I've searched around a bit as to why this is happening but can't really get any insights.

Any hints?

**Comment by lwm** [comment]
Please see https://github.com/jfloff/alpine-python/issues/28#issuecomment-410094133.

**Pull request closed without merging**
